version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node:14"

    steps:
      - checkout:
          path: ~/Application

      - add_ssh_keys:
          fingerprints:
            - "github.com"

      - run:
          name: Pull Repository
          command: git pull origin master
